# Generated by Django 5.2.3 on 2025-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0004_doctor_estudio_paciente_delete_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='urgencia',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10),
        ),
    ]
